package com.erik.bestiary.entity.renderer;

import com.erik.bestiary.BestiaryMod;
import com.erik.bestiary.entity.PackWolfEntity;
import com.erik.bestiary.entity.model.PackWolfModel;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.MobRenderer;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;
import net.minecraft.resources.Identifier;

/**
 * PackWolfRenderer — renders PackWolfEntity using our custom PackWolfModel.
 *
 * ★ V3 PATTERN: exact structure from OverworldDragonRenderer ★
 *
 * MobRenderer<E, S, M>:
 * - E = PackWolfEntity: the entity being rendered
 * - S = LivingEntityRenderState: standard render state (v3 pattern)
 * - M = PackWolfModel: our custom wolf-shaped model
 *
 * Using LivingEntityRenderState (same as dragon renderer) avoids
 * any WolfModel/WolfRenderState version compatibility issues.
 *
 * ─── Texture ──────────────────────────────────────────────────────────────────
 * assets/bestiary/textures/entity/pack_wolf.png — our dark gray pack wolf texture
 * Generated by Python PIL (64x32 wolf UV layout)
 */
public class PackWolfRenderer extends MobRenderer<PackWolfEntity, LivingEntityRenderState, PackWolfModel> {

    private static final Identifier PACK_WOLF_TEXTURE = Identifier.fromNamespaceAndPath(
            BestiaryMod.MOD_ID, "textures/entity/pack_wolf.png");

    /**
     * @param context provides bakeLayer() which links the model to its LayerDefinition
     */
    public PackWolfRenderer(EntityRendererProvider.Context context) {
        super(context,
                new PackWolfModel(context.bakeLayer(PackWolfModel.LAYER_LOCATION)),
                0.5f);  // Shadow radius: ~0.5 blocks (wolf-sized shadow)
    }

    /**
     * ★ V3 PATTERN: getTextureLocation returns our custom texture ★
     */
    @Override
    public Identifier getTextureLocation(LivingEntityRenderState state) {
        return PACK_WOLF_TEXTURE;
    }

    /**
     * ★ V3 PATTERN: createRenderState returns the render state type ★
     */
    @Override
    public LivingEntityRenderState createRenderState() {
        return new LivingEntityRenderState();
    }
}
